package org.verumomnis.forensic.report

import org.verumomnis.forensic.core.ForensicEvidence
import org.verumomnis.forensic.core.ForensicLocation
import org.verumomnis.forensic.crypto.CryptographicSeal
import org.verumomnis.forensic.crypto.CryptographicSealingEngine
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter

/**
 * Forensic Narrative Generator
 * 
 * Generates detailed, AI-readable narratives for forensic reports.
 * 
 * The narrative is designed to be:
 * 1. Comprehensive enough for any AI to provide legal advice
 * 2. Structured for machine parsing
 * 3. Human-readable for legal professionals
 * 4. Jurisdiction-aware for applicable law determination
 * 
 * Output Structure:
 * - Timeline + Facts + Contradictions + Violations + Guidance
 * - Machine and human readable format
 * - Complete evidence mapping
 */
class ForensicNarrativeGenerator {
    
    companion object {
        private const val VERSION = "1.0"
        private const val ENGINE = "Verum Omnis Constitutional Governance Layer"
    }
    
    /**
     * Generate a comprehensive forensic narrative for AI analysis
     */
    fun generateNarrative(
        evidence: ForensicEvidence,
        seal: CryptographicSeal,
        findings: List<ForensicFinding>,
        caseContext: CaseContext
    ): ForensicNarrative {
        val sections = mutableListOf<NarrativeSection>()
        
        // Section 1: Document Identification
        sections.add(generateDocumentIdentificationSection(evidence, seal))
        
        // Section 2: Temporal Context (Critical for AI legal analysis)
        sections.add(generateTemporalContextSection(evidence))
        
        // Section 3: Jurisdictional Context (Critical for applicable law)
        sections.add(generateJurisdictionalContextSection(evidence.location))
        
        // Section 4: Evidence Chain of Custody
        sections.add(generateChainOfCustodySection(evidence, seal))
        
        // Section 5: Document Content Analysis
        sections.add(generateContentAnalysisSection(evidence, findings))
        
        // Section 6: Detected Issues and Contradictions
        sections.add(generateContradictionsSection(findings))
        
        // Section 7: Rights and Compliance Analysis
        sections.add(generateRightsAnalysisSection(findings))
        
        // Section 8: AI Guidance Instructions
        sections.add(generateAIGuidanceSection(evidence, caseContext))
        
        // Section 9: Verification and Authenticity
        sections.add(generateVerificationSection(seal))
        
        return ForensicNarrative(
            version = VERSION,
            generatedAt = Instant.now(),
            evidenceId = evidence.evidenceId,
            sessionId = evidence.sessionId,
            sections = sections,
            fullText = sections.joinToString("\n\n") { it.toFormattedString() }
        )
    }
    
    private fun generateDocumentIdentificationSection(
        evidence: ForensicEvidence,
        seal: CryptographicSeal
    ): NarrativeSection {
        return NarrativeSection(
            title = "DOCUMENT IDENTIFICATION",
            sectionType = SectionType.IDENTIFICATION,
            content = """
                |FORENSIC EVIDENCE RECORD
                |========================
                |
                |This document constitutes a cryptographically sealed forensic record
                |generated by the $ENGINE.
                |
                |Evidence Identification:
                |  - Evidence ID: ${evidence.evidenceId}
                |  - Session ID: ${evidence.sessionId}
                |  - Document Type: ${evidence.documentType}
                |  - Original Filename: ${evidence.originalFilename ?: "N/A"}
                |  - Document Hash (SHA-512): ${evidence.originalHash}
                |
                |Seal Information:
                |  - Seal Algorithm: ${seal.algorithm}
                |  - Seal Version: ${seal.sealVersion}
                |  - Verification Code: ${seal.verificationCode}
                |
                |IMPORTANT FOR AI ANALYSIS:
                |This document is self-contained and cryptographically sealed. Any 
                |analysis or legal advice should consider all sections of this report.
                |The seal verification code can be used to verify document authenticity.
            """.trimMargin(),
            aiInstructions = "Use this section to identify the specific document being analyzed. The Evidence ID and Session ID provide unique identifiers for reference. The SHA-512 hash confirms document integrity.",
            metadata = mapOf(
                "evidence_id" to evidence.evidenceId,
                "session_id" to evidence.sessionId,
                "document_type" to evidence.documentType.name,
                "hash" to evidence.originalHash
            )
        )
    }
    
    private fun generateTemporalContextSection(evidence: ForensicEvidence): NarrativeSection {
        val captureTime = evidence.captureTimestampUtc
        val localTime = evidence.getLocalCaptureTime()
        val timezone = evidence.captureTimezone
        
        return NarrativeSection(
            title = "TEMPORAL CONTEXT",
            sectionType = SectionType.TEMPORAL,
            content = """
                |TEMPORAL CONTEXT FOR LEGAL ANALYSIS
                |===================================
                |
                |Evidence Capture Timestamp:
                |  - UTC Time: ${evidence.getIsoTimestamp()}
                |  - Local Time: $localTime
                |  - Timezone: ${timezone.id}
                |
                |Date Components (for statute of limitations analysis):
                |  - Year: ${captureTime.atZone(timezone).year}
                |  - Month: ${captureTime.atZone(timezone).monthValue}
                |  - Day: ${captureTime.atZone(timezone).dayOfMonth}
                |  - Day of Week: ${captureTime.atZone(timezone).dayOfWeek}
                |
                |CRITICAL FOR LEGAL AI:
                |When providing legal advice, consider:
                |  1. Applicable statutes of limitations based on this date
                |  2. Law versions in effect on this date
                |  3. Business hours/days for procedural requirements
                |  4. Any time-sensitive filing requirements
            """.trimMargin(),
            aiInstructions = "This section provides the exact timestamp when evidence was captured. Use the UTC time for cross-jurisdictional analysis and the local time for jurisdiction-specific deadlines. Consider any time-sensitive legal requirements.",
            metadata = mapOf(
                "utc_timestamp" to evidence.getIsoTimestamp(),
                "local_time" to localTime,
                "timezone" to timezone.id
            )
        )
    }
    
    private fun generateJurisdictionalContextSection(location: ForensicLocation): NarrativeSection {
        return NarrativeSection(
            title = "JURISDICTIONAL CONTEXT",
            sectionType = SectionType.JURISDICTION,
            content = """
                |JURISDICTIONAL CONTEXT FOR LEGAL ANALYSIS
                |=========================================
                |
                |CAPTURE LOCATION:
                |  - Coordinates: ${location.getCoordinatesString()}
                |  - GPS Accuracy: ${if (location.accuracyMeters > 0) "${location.accuracyMeters}m" else "Manual Entry"}
                |  - Altitude: ${location.altitudeMeters?.let { "${it}m above sea level" } ?: "Not recorded"}
                |
                |JURISDICTION DETAILS:
                |  - Country: ${location.country ?: "Unknown"}
                |  - Country Code: ${location.countryCode ?: "Unknown"}
                |  - State/Province: ${location.administrativeArea ?: "Unknown"}
                |  - City/Locality: ${location.locality ?: "Unknown"}
                |  - Full Address: ${location.fullAddress ?: "Not available"}
                |  - Timezone: ${location.timezoneId}
                |
                |JURISDICTION STRING: ${location.getJurisdictionString()}
                |
                |CRITICAL FOR LEGAL AI:
                |When providing legal advice, determine:
                |  1. PRIMARY JURISDICTION: ${location.country ?: "Unknown"} (${location.countryCode ?: "???"})
                |  2. SUB-JURISDICTION: ${location.administrativeArea ?: "Unknown"}
                |  3. LOCAL JURISDICTION: ${location.locality ?: "Unknown"}
                |
                |Apply the laws of these jurisdictions in order of specificity.
                |Consider:
                |  - Federal/National laws of ${location.country ?: "the relevant country"}
                |  - State/Provincial laws of ${location.administrativeArea ?: "the relevant region"}
                |  - Local ordinances of ${location.locality ?: "the relevant locality"}
                |  - Any applicable international treaties or conventions
                |
                |LEGAL SYSTEM INDICATION:
                |  Based on country code "${location.countryCode ?: "Unknown"}":
                |  ${getLegalSystemDescription(location.countryCode)}
            """.trimMargin(),
            aiInstructions = "This section provides complete jurisdictional context. Use the country code and administrative area to determine applicable laws. The legal system indication helps identify whether common law, civil law, or other legal systems apply.",
            metadata = mapOf(
                "country" to (location.country ?: "Unknown"),
                "country_code" to (location.countryCode ?: "Unknown"),
                "administrative_area" to (location.administrativeArea ?: "Unknown"),
                "locality" to (location.locality ?: "Unknown"),
                "coordinates" to "${location.latitude},${location.longitude}",
                "timezone" to location.timezoneId
            )
        )
    }
    
    private fun getLegalSystemDescription(countryCode: String?): String {
        return when (countryCode?.uppercase()) {
            "ZA" -> "South African law applies (mixed legal system: Roman-Dutch civil law + English common law). Constitution of South Africa is supreme."
            "US" -> "United States law applies (common law system). Federal and state laws may both apply."
            "GB", "UK" -> "United Kingdom law applies (common law system). Consider England/Wales, Scotland, or Northern Ireland specific laws."
            "AU" -> "Australian law applies (common law system). Federal and state/territory laws may both apply."
            "CA" -> "Canadian law applies (mixed: common law except Quebec which uses civil law)."
            "IN" -> "Indian law applies (common law system). Federal and state laws may both apply."
            "DE" -> "German law applies (civil law system based on codified law)."
            "FR" -> "French law applies (civil law system based on Napoleonic Code)."
            "JP" -> "Japanese law applies (civil law system with German and American influences)."
            "BR" -> "Brazilian law applies (civil law system based on codified law)."
            "NG" -> "Nigerian law applies (mixed: common law + customary law + Sharia in some states)."
            "KE" -> "Kenyan law applies (common law system with constitutional supremacy)."
            else -> "Legal system unknown. AI should research applicable legal system for country code '$countryCode'."
        }
    }
    
    private fun generateChainOfCustodySection(
        evidence: ForensicEvidence,
        seal: CryptographicSeal
    ): NarrativeSection {
        return NarrativeSection(
            title = "CHAIN OF CUSTODY",
            sectionType = SectionType.CHAIN_OF_CUSTODY,
            content = """
                |CHAIN OF CUSTODY DOCUMENTATION
                |==============================
                |
                |CAPTURE DEVICE INFORMATION:
                |  - Manufacturer: ${evidence.deviceInfo.manufacturer}
                |  - Model: ${evidence.deviceInfo.model}
                |  - Android Version: ${evidence.deviceInfo.androidVersion}
                |  - SDK Version: ${evidence.deviceInfo.sdkVersion}
                |  - Device ID (Anonymized): ${evidence.deviceInfo.deviceId}
                |
                |CAPTURE METHODOLOGY:
                |  - Document was captured using Verum Omnis Forensic Engine v1.0
                |  - Capture occurred at: ${evidence.getLocalCaptureTime()}
                |  - Location at capture: ${evidence.location.getJurisdictionString()}
                |  - Capture was performed in stateless, offline mode
                |  - No data was transmitted to external servers
                |
                |CRYPTOGRAPHIC SEALING:
                |  - Seal applied at: ${seal.timestamp}
                |  - Sealing algorithm: ${seal.algorithm}
                |  - Document hash at sealing: ${seal.documentHash}
                |  - Location hash included: ${seal.locationHash}
                |  - Seal signature: ${seal.signature.take(32)}...
                |
                |INTEGRITY VERIFICATION:
                |  - Verification Code: ${seal.verificationCode}
                |  - To verify: Compare this code with QR code scan
                |  - Any modification to document will invalidate seal
                |
                |CHAIN OF CUSTODY ATTESTATION:
                |  This document has remained under cryptographic seal since capture.
                |  The hash algorithm (${seal.algorithm}) ensures any modification
                |  would be immediately detectable.
            """.trimMargin(),
            aiInstructions = "This section establishes chain of custody for legal admissibility. The cryptographic seal provides tamper-evident protection. Note that the document was captured offline with no external data transmission.",
            metadata = mapOf(
                "device_manufacturer" to evidence.deviceInfo.manufacturer,
                "device_model" to evidence.deviceInfo.model,
                "seal_algorithm" to seal.algorithm,
                "verification_code" to seal.verificationCode
            )
        )
    }
    
    private fun generateContentAnalysisSection(
        evidence: ForensicEvidence,
        findings: List<ForensicFinding>
    ): NarrativeSection {
        val contentFindings = findings.filter { it.type == FindingType.CONTENT_OBSERVATION }
        
        return NarrativeSection(
            title = "DOCUMENT CONTENT ANALYSIS",
            sectionType = SectionType.CONTENT,
            content = """
                |DOCUMENT CONTENT ANALYSIS
                |=========================
                |
                |EXTRACTED TEXT CONTENT:
                |${evidence.extractedText.ifEmpty { "[No text content extracted]" }}
                |
                |DOCUMENT METADATA:
                |${evidence.documentMetadata.entries.joinToString("\n") { "  - ${it.key}: ${it.value}" }}
                |
                |OCR CONFIDENCE: ${(evidence.ocrConfidence * 100).toInt()}%
                |
                |CONTENT OBSERVATIONS:
                |${contentFindings.joinToString("\n") { "  - ${it.description}" }.ifEmpty { "  - No specific content observations" }}
                |
                |NOTE FOR AI ANALYSIS:
                |The extracted text above represents the machine-readable content of the
                |original document. Use this text for legal analysis, contract review,
                |or compliance checking. The OCR confidence indicates reliability.
            """.trimMargin(),
            aiInstructions = "This section contains the actual document content. Analyze the extracted text for legal implications, contractual obligations, potential issues, or compliance matters relevant to the jurisdiction identified above.",
            metadata = mapOf(
                "ocr_confidence" to evidence.ocrConfidence.toString(),
                "text_length" to evidence.extractedText.length.toString()
            )
        )
    }
    
    private fun generateContradictionsSection(findings: List<ForensicFinding>): NarrativeSection {
        val contradictions = findings.filter { 
            it.type == FindingType.CONTRADICTION || 
            it.type == FindingType.INCONSISTENCY 
        }
        val issues = findings.filter { it.type == FindingType.POTENTIAL_ISSUE }
        
        return NarrativeSection(
            title = "CONTRADICTIONS AND ISSUES",
            sectionType = SectionType.CONTRADICTIONS,
            content = """
                |DETECTED CONTRADICTIONS AND ISSUES
                |==================================
                |
                |CONTRADICTIONS DETECTED: ${contradictions.size}
                |${if (contradictions.isEmpty()) "  None detected" else contradictions.mapIndexed { i, f -> 
                    "  ${i + 1}. [${f.severity}] ${f.description}\n     Evidence: ${f.evidenceReference ?: "N/A"}"
                }.joinToString("\n")}
                |
                |POTENTIAL ISSUES: ${issues.size}
                |${if (issues.isEmpty()) "  None detected" else issues.mapIndexed { i, f -> 
                    "  ${i + 1}. [${f.severity}] ${f.description}\n     Recommendation: ${f.recommendation ?: "Review required"}"
                }.joinToString("\n")}
                |
                |CONTRADICTION ANALYSIS METHODOLOGY:
                |  The following layers were analyzed:
                |  - Timeline analysis
                |  - Statement comparison
                |  - Behavioral inconsistencies
                |  - Document metadata mismatches
                |  - Financial flows (if applicable)
                |  - Coercion indicators
                |  - Rights violations
                |  - Intent vs action mismatch
                |
                |AI GUIDANCE:
                |  Review each contradiction and issue in context of applicable law.
                |  Consider whether issues rise to level of legal concern.
            """.trimMargin(),
            aiInstructions = "This section highlights potential contradictions and issues detected in the document. Each finding should be evaluated in context of the applicable jurisdiction. Contradictions may indicate fraud, coercion, or error requiring legal attention.",
            metadata = mapOf(
                "contradiction_count" to contradictions.size.toString(),
                "issue_count" to issues.size.toString()
            )
        )
    }
    
    private fun generateRightsAnalysisSection(findings: List<ForensicFinding>): NarrativeSection {
        val rightsFindings = findings.filter { 
            it.type == FindingType.RIGHTS_CONCERN || 
            it.type == FindingType.COERCION_INDICATOR 
        }
        
        return NarrativeSection(
            title = "RIGHTS AND COMPLIANCE ANALYSIS",
            sectionType = SectionType.RIGHTS,
            content = """
                |RIGHTS AND COMPLIANCE ANALYSIS
                |==============================
                |
                |RIGHTS CONCERNS IDENTIFIED: ${rightsFindings.size}
                |${if (rightsFindings.isEmpty()) "  No rights concerns identified" else rightsFindings.mapIndexed { i, f -> 
                    "  ${i + 1}. [${f.severity}] ${f.description}\n     Category: ${f.category ?: "General"}"
                }.joinToString("\n")}
                |
                |COMPLIANCE AREAS REVIEWED:
                |  - Human rights implications
                |  - Consumer protection compliance
                |  - Data protection / Privacy
                |  - Fair dealing requirements
                |  - Anti-coercion provisions
                |  - Disclosure requirements
                |
                |VERUM OMNIS CORE PRINCIPLES APPLIED:
                |  1. TRUTH: Prioritized factual accuracy and verifiable evidence
                |  2. FAIRNESS: Checked for protection of vulnerable parties
                |  3. HUMAN RIGHTS: Reviewed for dignity, equality, agency concerns
                |  4. INTEGRITY: Checked for manipulation or bias
                |  5. INDEPENDENCE: Analysis performed without external influence
                |
                |AI GUIDANCE:
                |  Review rights concerns in context of:
                |  - Constitutional rights in the jurisdiction
                |  - Statutory protections available
                |  - Common law/civil law remedies
                |  - International human rights standards
            """.trimMargin(),
            aiInstructions = "This section identifies potential rights violations or compliance issues. When providing legal advice, consider available remedies under the applicable jurisdiction's laws and any relevant international frameworks.",
            metadata = mapOf(
                "rights_concerns_count" to rightsFindings.size.toString()
            )
        )
    }
    
    private fun generateAIGuidanceSection(
        evidence: ForensicEvidence,
        caseContext: CaseContext
    ): NarrativeSection {
        return NarrativeSection(
            title = "AI LEGAL ANALYSIS GUIDANCE",
            sectionType = SectionType.AI_GUIDANCE,
            content = """
                |INSTRUCTIONS FOR AI LEGAL ANALYSIS
                |==================================
                |
                |CASE CONTEXT:
                |  - Case Type: ${caseContext.caseType}
                |  - User Description: ${caseContext.userDescription}
                |  - Urgency Level: ${caseContext.urgency}
                |  - Related Matters: ${caseContext.relatedMatters.joinToString(", ").ifEmpty { "None specified" }}
                |
                |JURISDICTION SUMMARY:
                |  - Primary: ${evidence.location.country ?: "Unknown"} (${evidence.location.countryCode ?: "??"})
                |  - Sub-Jurisdiction: ${evidence.location.administrativeArea ?: "Unknown"}
                |  - Local: ${evidence.location.locality ?: "Unknown"}
                |  - Timestamp: ${evidence.getLocalCaptureTime()}
                |
                |WHEN PROVIDING LEGAL ADVICE, PLEASE:
                |
                |1. IDENTIFY APPLICABLE LAW:
                |   - Reference specific statutes, codes, or precedents
                |   - Note any recent amendments or changes
                |   - Consider both substantive and procedural law
                |
                |2. ANALYZE THE FACTS:
                |   - Review the document content section above
                |   - Note any contradictions or issues identified
                |   - Consider chain of custody and evidence integrity
                |
                |3. ASSESS RIGHTS AND OBLIGATIONS:
                |   - What rights does the subject have?
                |   - What obligations arise from the document?
                |   - Are there any violations or breaches?
                |
                |4. RECOMMEND ACTIONS:
                |   - Immediate steps if required
                |   - Time-sensitive matters (statutes of limitations)
                |   - Preservation of evidence requirements
                |   - Recommended legal consultation
                |
                |5. CONSIDER PRACTICAL ASPECTS:
                |   - Court or tribunal with jurisdiction
                |   - Likely procedures and timelines
                |   - Costs and resources required
                |   - Alternative dispute resolution options
                |
                |IMPORTANT DISCLAIMER:
                |  This forensic report provides factual documentation only.
                |  AI analysis should be reviewed by qualified legal professionals
                |  before acting on any recommendations.
            """.trimMargin(),
            aiInstructions = "This section provides guidance for AI systems analyzing this report. Follow the structured approach outlined to provide comprehensive legal analysis.",
            metadata = mapOf(
                "case_type" to caseContext.caseType,
                "urgency" to caseContext.urgency.name
            )
        )
    }
    
    private fun generateVerificationSection(seal: CryptographicSeal): NarrativeSection {
        return NarrativeSection(
            title = "VERIFICATION AND AUTHENTICITY",
            sectionType = SectionType.VERIFICATION,
            content = """
                |DOCUMENT VERIFICATION INFORMATION
                |=================================
                |
                |CRYPTOGRAPHIC SEAL SUMMARY:
                |${seal.getSealSummary()}
                |
                |QR CODE VERIFICATION:
                |  Scan the QR code on this document to verify:
                |  Expected Code: ${seal.verificationCode}
                |  QR Content: ${seal.getQrCodeContent()}
                |
                |VERIFICATION INSTRUCTIONS:
                |  1. Scan QR code with any QR reader
                |  2. Compare verification code with above
                |  3. If codes match, document is authentic
                |  4. If codes differ, document may be tampered
                |
                |HASH VERIFICATION (Technical):
                |  Algorithm: ${seal.algorithm}
                |  Document Hash: ${seal.documentHash}
                |  Location Hash: ${seal.locationHash}
                |  Session ID: ${seal.sessionId}
                |  Signature: ${seal.signature}
                |
                |VERUM OMNIS ATTESTATION:
                |  This document was created using the Verum Omnis Constitutional
                |  Governance Layer forensic engine. It adheres to the following
                |  standards:
                |  
                |  - Offline-first, stateless operation
                |  - No external data transmission
                |  - SHA-512 cryptographic sealing
                |  - PDF 1.7 standard compliance
                |  - Legal-grade evidence documentation
                |  
                |  Engine Version: 1.0
                |  Constitution Version: 1.0
                |  
                |  Creator: Liam Highcock
                |  Foundation: Verum Global Foundation
            """.trimMargin(),
            aiInstructions = "This section provides verification information for the document's authenticity. The cryptographic seal ensures document integrity. When analyzing this report, note that its authenticity is verifiable.",
            metadata = mapOf(
                "verification_code" to seal.verificationCode,
                "algorithm" to seal.algorithm
            )
        )
    }
}

/**
 * Complete forensic narrative document
 */
data class ForensicNarrative(
    val version: String,
    val generatedAt: Instant,
    val evidenceId: String,
    val sessionId: String,
    val sections: List<NarrativeSection>,
    val fullText: String
)

/**
 * Individual narrative section
 */
data class NarrativeSection(
    val title: String,
    val sectionType: SectionType,
    val content: String,
    val aiInstructions: String,
    val metadata: Map<String, String>
) {
    fun toFormattedString(): String {
        return """
            |========================================================================
            |$title
            |========================================================================
            |
            |$content
            |
            |[AI INSTRUCTION: $aiInstructions]
        """.trimMargin()
    }
}

/**
 * Section types for structured parsing
 */
enum class SectionType {
    IDENTIFICATION,
    TEMPORAL,
    JURISDICTION,
    CHAIN_OF_CUSTODY,
    CONTENT,
    CONTRADICTIONS,
    RIGHTS,
    AI_GUIDANCE,
    VERIFICATION
}

/**
 * Case context provided by user
 */
data class CaseContext(
    val caseType: String,
    val userDescription: String,
    val urgency: Urgency,
    val relatedMatters: List<String> = emptyList()
)

/**
 * Urgency levels
 */
enum class Urgency {
    LOW,
    MEDIUM,
    HIGH,
    CRITICAL
}

/**
 * Forensic finding from document analysis
 */
data class ForensicFinding(
    val type: FindingType,
    val severity: Severity,
    val description: String,
    val evidenceReference: String? = null,
    val recommendation: String? = null,
    val category: String? = null
)

/**
 * Finding types
 */
enum class FindingType {
    CONTENT_OBSERVATION,
    CONTRADICTION,
    INCONSISTENCY,
    POTENTIAL_ISSUE,
    RIGHTS_CONCERN,
    COERCION_INDICATOR,
    METADATA_MISMATCH,
    FINANCIAL_ANOMALY
}

/**
 * Severity levels
 */
enum class Severity {
    INFO,
    LOW,
    MEDIUM,
    HIGH,
    CRITICAL
}
