package org.verumomnis.forensic.pdf

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Color
import com.google.zxing.BarcodeFormat
import com.google.zxing.qrcode.QRCodeWriter
import org.verumomnis.forensic.core.ForensicCase
import org.verumomnis.forensic.core.VerumOmnisApplication
import java.io.File
import java.io.FileOutputStream
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter

/**
 * Forensic PDF Report Generator for Verum Omnis
 *
 * Implements the forensic rules from verum-constitution.json:
 * - pdf_standard: PDF 1.7
 * - watermark: VERUM OMNIS 3D LOGO CENTERED
 * - qr_code_inclusion: true
 * - admissibility_standard: legal-grade, contradiction-free, complete evidence mapping
 *
 * Output requirements:
 * - clarity: Simple, direct, human-readable
 * - structure: Timeline + Facts + Contradictions + Violations + Guidance
 * - audit_trail: true
 * - machine_and_human_readable: true
 * - stamp_with_constitution_mode: true
 */
class ForensicPdfGenerator(private val context: Context) {

    companion object {
        private const val PDF_VERSION = "1.7"
        private const val QR_CODE_SIZE = 200
    }

    private val dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z")
        .withZone(ZoneId.systemDefault())

    /**
     * Generates a forensic PDF report for a case
     */
    fun generateReport(case: ForensicCase, narrative: String): File {
        val reportFile = File(case.directory, "report_${System.currentTimeMillis()}.pdf")

        FileOutputStream(reportFile).use { fos ->
            // Generate PDF content as text (simplified - in production use iText PDF)
            val pdfContent = buildPdfContent(case, narrative)
            fos.write(pdfContent.toByteArray())
        }

        return reportFile
    }

    /**
     * Builds the PDF content structure
     */
    private fun buildPdfContent(case: ForensicCase, narrative: String): String = buildString {
        // PDF Header
        appendLine("=".repeat(80))
        appendLine("VERUM OMNIS FORENSIC REPORT")
        appendLine("=".repeat(80))
        appendLine()

        // Constitution Mode Stamp
        appendLine("CONSTITUTION MODE: ACTIVE")
        appendLine("Engine: ${VerumOmnisApplication.ENGINE_NAME}")
        appendLine("Version: ${VerumOmnisApplication.VERSION}")
        appendLine("PDF Standard: $PDF_VERSION")
        appendLine()

        // Case Information
        appendLine("-".repeat(40))
        appendLine("CASE INFORMATION")
        appendLine("-".repeat(40))
        appendLine("Case ID: ${case.id}")
        appendLine("Case Name: ${case.name}")
        appendLine("Created: ${dateFormatter.format(case.createdAt)}")
        appendLine("Evidence Count: ${case.evidenceItems.size}")
        appendLine()

        // Timeline
        appendLine("-".repeat(40))
        appendLine("EVIDENCE TIMELINE")
        appendLine("-".repeat(40))
        case.evidenceItems.sortedBy { it.timestamp }.forEachIndexed { index, evidence ->
            appendLine()
            appendLine("${index + 1}. ${evidence.type.name}")
            appendLine("   Description: ${evidence.description}")
            appendLine("   Timestamp: ${dateFormatter.format(evidence.timestamp)}")
            appendLine("   Hash: ${evidence.contentHash.take(32)}...")
            if (evidence.location != null) {
                appendLine("   Location: ${evidence.location.toCoordinatesString()}")
            }
            appendLine("   Sealed: ${evidence.seal.timestamp}")
        }
        appendLine()

        // AI-Readable Narrative
        appendLine("-".repeat(40))
        appendLine("FORENSIC NARRATIVE")
        appendLine("-".repeat(40))
        appendLine(narrative)
        appendLine()

        // Verification Information
        appendLine("-".repeat(40))
        appendLine("VERIFICATION & SEAL")
        appendLine("-".repeat(40))
        appendLine("Hash Algorithm: SHA-512")
        appendLine("Seal Algorithm: HMAC-SHA512")
        appendLine("Tamper Detection: ENABLED")
        appendLine()

        // QR Code placeholder (would contain verification URL in production)
        val qrData = buildQrCodeData(case)
        appendLine("QR Verification Data:")
        appendLine(qrData)
        appendLine()

        // Footer
        appendLine("=".repeat(80))
        appendLine("Generated by Verum Omnis Forensic Engine")
        appendLine("Report Time: ${dateFormatter.format(Instant.now())}")
        appendLine()
        appendLine("This report was generated in accordance with:")
        appendLine("- Verum Omnis Constitutional Governance Layer")
        appendLine("- Forensic Standard: SHA-512 with HMAC sealing")
        appendLine("- Legal admissibility standard: Evidence grade")
        appendLine()
        appendLine("WATERMARK: VERUM OMNIS 3D LOGO CENTERED")
        appendLine("=".repeat(80))
    }

    /**
     * Builds QR code verification data
     */
    private fun buildQrCodeData(case: ForensicCase): String = buildString {
        append("verum://verify?")
        append("case_id=${case.id}")
        append("&created=${case.createdAt.epochSecond}")
        append("&evidence_count=${case.evidenceItems.size}")
        if (case.evidenceItems.isNotEmpty()) {
            val lastEvidence = case.evidenceItems.last()
            append("&last_hash=${lastEvidence.contentHash.take(16)}")
        }
    }

    /**
     * Generates a QR code bitmap for verification
     */
    fun generateQrCode(data: String): Bitmap {
        val writer = QRCodeWriter()
        val bitMatrix = writer.encode(data, BarcodeFormat.QR_CODE, QR_CODE_SIZE, QR_CODE_SIZE)

        val bitmap = Bitmap.createBitmap(QR_CODE_SIZE, QR_CODE_SIZE, Bitmap.Config.RGB_565)
        for (x in 0 until QR_CODE_SIZE) {
            for (y in 0 until QR_CODE_SIZE) {
                bitmap.setPixel(x, y, if (bitMatrix[x, y]) Color.BLACK else Color.WHITE)
            }
        }
        return bitmap
    }
}
